### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by devbn3li** [dragonsbootcampllc/Spotalent#5]
![image](https://github.com/user-attachments/assets/a68b35da-9595-4ade-9a82-62e03ccde347)

put in your mind this not static data, pass it as props

**Comment by 1zizo1** [comment]
hi here is what i done 

![WhatsApp Image 2024-08-20 at 19 36 59_38ee9160](https://github.com/user-attachments/assets/2ed48d74-12a7-4605-b635-1ea6daa1f832)
Responsive:

![WhatsApp Image 2024-08-20 at 19 37 27_6c788a6d](https://github.com/user-attachments/assets/447992db-c6af-41c1-a71f-a47cb8171c5e)
![WhatsApp Image 2024-08-20 at 19 37 47_cb44c5c2](https://github.com/user-attachments/assets/fa58dd86-20d2-4b0c-9c96-d74a214752b3)
