### ISSUE TITLE
Jobs page

### ISSUE THREAD

**Issue by devbn3li** [dragonsbootcampllc/Spotalent#7]
![image](https://github.com/user-attachments/assets/c4b6aad3-9777-44b6-aa57-de06c16a8be3)

enable users to search, filter and compare by job title, location, skills

**Comment by AyaA1i** [comment]
![2](https://github.com/user-attachments/assets/60273828-91b2-4df5-b67f-d7405f22b439)
![1](https://github.com/user-attachments/assets/7554a742-7f3a-44a1-907b-e9134b48b518)
